# Numpy

In [3]:
import numpy as np # ALIAS


In [ ]:
#range(stop,start,step)

In [4]:
print(list(range(100)))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [6]:
print(list(range(10,100)))


[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [9]:
print(list(range(10,100,5)))

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [9]:
a = np.arange(30)

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
(a,b)  # matrix of a rows and b columns

In [11]:
a = np.arange(30,100)   # no of elements  : 70
a = a.reshape(10,7)

In [13]:
a.shape


(10, 7)

In [42]:
a



array([[30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [43]:
a = np.arange(30,100).reshape(10,7)


In [44]:
a

array([[30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [14]:
a.shape


(10, 7)

In [15]:
a.ndim


2

In [47]:
a

array([[30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [ ]:
arr1.property_name  # properties of the array
arr1.function_name()  #call a function on arr1/data str.

In [16]:
a.dtype


dtype('int32')

In [17]:
a.size



70

In [17]:
type(a)


numpy.ndarray

In [262]:
b = np.array([6, 7, 8,66])

b

array([ 6,  7,  8, 66])

In [57]:
b = np.array([[1,2,3,4],[5,6,7,8],[7,6,7,8]])

In [ ]:
a homogenious collection of elements in a data structure.

In [58]:
# TO CREATE AN ARRAY USING np.array([[e1,e2,e3],[e4,e5,e6]])

In [61]:
b.dtype

dtype('int32')

In [48]:
a = np.array([1,2,3,4])  # RIGHT
a

array([1, 2, 3, 4])

In [23]:
# array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [65]:
aa = np.array([34,34.5,"sunday"])

In [67]:
aa.dtype

dtype('<U32')

In [64]:
#The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2.2], [3,4] ],dtype=str)
c

array([['1', '2.2'],
       ['3', '4']], dtype='<U3')

In [68]:
np.zeros((3,4))  # zero matrix/zero array:
#The function zeros creates an array full of zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
np.ones((3,4))# create a matrix filled with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
a

array([1, 2, 3, 4])

In [71]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [73]:
degrees=[30,45,60,90]

In [74]:
np.sin(degrees)

array([-0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [75]:
np.cos(degrees)

array([ 0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [18]:
#universal functions such as sqrt, sin, cos etc.,
C = np.arange(3)

np.sqrt(C)

array([0.        , 1.        , 1.41421356])

In [77]:
#Indexing Arrays
a = np.arange(100).reshape(20,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [79]:
a[4][1]   #indexing : to access a single element in a N dimensional array.  a[i][j]: i--> row pointer,
# j --> column pointer

21

In [78]:
a.shape

(20, 5)

In [273]:
a[1][3]----> array indexing -->arr[i][j] to access the eleemnt at pos (i,j)

8

In [80]:
#Shape Manipulation
a = np.arange(12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
a = np.arange(4).reshape(2,2)
b = np.arange(11,15).reshape(2,2)
print(a)
print(b)


[[0 1]
 [2 3]]
[[11 12]
 [13 14]]


In [ ]:
stacking

In [86]:
np.vstack((a,b))  # vertical stacking : place one array on top of the other: number of columns should match


array([[ 0,  1],
       [ 2,  3],
       [11, 12],
       [13, 14]])

In [87]:
np.hstack((a,b)) # horizontal stacking: one next to the other . number of rows of the 2 arrays should match.


array([[ 0,  1, 11, 12],
       [ 2,  3, 13, 14]])

In [89]:
np.floor(5.7)

5.0

In [ ]:
45.65# floor of 45.65--> 45,ceiling of 45.65 --> 46

In [91]:
a = np.arange(2,26).reshape(6,4)

In [104]:
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [106]:
hs1,hs2=np.hsplit(a,2)   # Split a into 2 horizontal parts

In [108]:
vs1,vs2,vs3=np.vsplit(a,3)

In [284]:
#Copy
#view
#referrence
a = np.arange(12).reshape(3,4)
a.shape

(3, 4)

In [308]:
a#shallow copy
b=a

In [304]:
a=a.reshape(1,12)

In [309]:
a.shape

(1, 12)

In [313]:
b=a

In [339]:
a.shape

(3, 4)

In [338]:
a.resize(3,4)

In [329]:
s=np.arange(0,20).reshape(4,5)

In [335]:
s=s.reshape(10,2)
ss.shape

(4, 5)

In [331]:
ss=s.copy()

In [332]:
ss

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [325]:
# View or Shallow Copy
c = a.view()#--> view the array as it as /as a mirror image.



In [327]:
c is a

False

In [45]:
c.base is a  
a.shape
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
c.shape = 2,6                      # a's shape doesn't change
print(a.shape)
c

(3, 4)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [47]:
c[0,4] = 999                    # a's data changes
c

array([[  0,   1,   2,   3, 999,   5],
       [  6,   7,   8,   9,  10,  11]])

In [316]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [317]:
# Deep Copy
d = a.copy() #---> create a deep copy.


In [318]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [320]:
a=a.reshape(2,6)

In [321]:
a.shape

(2, 6)

In [322]:
d.shape

(1, 12)